
	ui->screen_FirstBoot_Setupdone_Header = lv_label_create(ui->screen_FirstBoot_Setupdone);
	lv_label_set_text(ui->screen_FirstBoot_Setupdone_Header, "Setup Done");
	lv_label_set_long_mode(ui->screen_FirstBoot_Setupdone_Header, LV_LABEL_LONG_WRAP);
	lv_obj_set_pos(ui->screen_FirstBoot_Setupdone_Header, 20, 32);
	lv_obj_set_size(ui->screen_FirstBoot_Setupdone_Header, 680, 80);
	lv_obj_set_style_border_width(ui->screen_FirstBoot_Setupdone_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_radius(ui->screen_FirstBoot_Setupdone_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_color(ui->screen_FirstBoot_Setupdone_Header, lv_color_hex(0xffffff), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui->screen_FirstBoot_Setupdone_Header, &lumi_font_helvetica_48, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui->screen_FirstBoot_Setupdone_Header, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_letter_space(ui->screen_FirstBoot_Setupdone_Header, 2, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_line_space(ui->screen_FirstBoot_Setupdone_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui->screen_FirstBoot_Setupdone_Header, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(ui->screen_FirstBoot_Setupdone_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_top(ui->screen_FirstBoot_Setupdone_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_right(ui->screen_FirstBoot_Setupdone_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_bottom(ui->screen_FirstBoot_Setupdone_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_left(ui->screen_FirstBoot_Setupdone_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_width(ui->screen_FirstBoot_Setupdone_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);

	
	ui->screen_FirstBoot_Setupdone_label_Content = lv_label_create(ui->screen_FirstBoot_Setupdone);
	lv_label_set_text(ui->screen_FirstBoot_Setupdone_label_Content, "Switch panel\nsetup complete.");
	lv_label_set_long_mode(ui->screen_FirstBoot_Setupdone_label_Content, LV_LABEL_LONG_WRAP);
	lv_obj_set_pos(ui->screen_FirstBoot_Setupdone_label_Content, 20, 295);
	lv_obj_set_size(ui->screen_FirstBoot_Setupdone_label_Content, 680, 130);
	lv_obj_set_style_border_width(ui->screen_FirstBoot_Setupdone_label_Content, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_radius(ui->screen_FirstBoot_Setupdone_label_Content, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_color(ui->screen_FirstBoot_Setupdone_label_Content, lv_color_hex(0xffffff), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui->screen_FirstBoot_Setupdone_label_Content, &lumi_font_helvetica_40, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui->screen_FirstBoot_Setupdone_label_Content, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_letter_space(ui->screen_FirstBoot_Setupdone_label_Content, 2, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_line_space(ui->screen_FirstBoot_Setupdone_label_Content, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui->screen_FirstBoot_Setupdone_label_Content, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(ui->screen_FirstBoot_Setupdone_label_Content, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_top(ui->screen_FirstBoot_Setupdone_label_Content, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_right(ui->screen_FirstBoot_Setupdone_label_Content, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_bottom(ui->screen_FirstBoot_Setupdone_label_Content, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_left(ui->screen_FirstBoot_Setupdone_label_Content, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_width(ui->screen_FirstBoot_Setupdone_label_Content, 0, LV_PART_MAIN|LV_STATE_DEFAULT);

	
	ui->screen_FirstBoot_Setupdone_btn_Gotodashboard = lv_btn_create(ui->screen_FirstBoot_Setupdone);
	ui->screen_FirstBoot_Setupdone_btn_Gotodashboard_label = lv_label_create(ui->screen_FirstBoot_Setupdone_btn_Gotodashboard);
	lv_label_set_text(ui->screen_FirstBoot_Setupdone_btn_Gotodashboard_label, "Go to dashboard");
	lv_label_set_long_mode(ui->screen_FirstBoot_Setupdone_btn_Gotodashboard_label, LV_LABEL_LONG_WRAP);
	lv_obj_align(ui->screen_FirstBoot_Setupdone_btn_Gotodashboard_label, LV_ALIGN_CENTER, 0, 0);
	lv_obj_set_style_pad_all(ui->screen_FirstBoot_Setupdone_btn_Gotodashboard, 0, LV_STATE_DEFAULT);
	lv_obj_set_width(ui->screen_FirstBoot_Setupdone_btn_Gotodashboard_label, LV_PCT(100));
	lv_obj_set_pos(ui->screen_FirstBoot_Setupdone_btn_Gotodashboard, 20, 607);
	lv_obj_set_size(ui->screen_FirstBoot_Setupdone_btn_Gotodashboard, 680, 92);
	lv_obj_set_style_bg_opa(ui->screen_FirstBoot_Setupdone_btn_Gotodashboard, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_color(ui->screen_FirstBoot_Setupdone_btn_Gotodashboard, lv_color_hex(0x1c1c1c), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_grad_dir(ui->screen_FirstBoot_Setupdone_btn_Gotodashboard, LV_GRAD_DIR_NONE, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_border_width(ui->screen_FirstBoot_Setupdone_btn_Gotodashboard, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_radius(ui->screen_FirstBoot_Setupdone_btn_Gotodashboard, 50, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_width(ui->screen_FirstBoot_Setupdone_btn_Gotodashboard, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_color(ui->screen_FirstBoot_Setupdone_btn_Gotodashboard, lv_color_hex(0xffffff), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui->screen_FirstBoot_Setupdone_btn_Gotodashboard, &lumi_font_helvetica_40, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui->screen_FirstBoot_Setupdone_btn_Gotodashboard, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui->screen_FirstBoot_Setupdone_btn_Gotodashboard, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN|LV_STATE_DEFAULT);
