
	ui->screen_FirstBoot_Welcome_Header = lv_label_create(ui->screen_FirstBoot_Welcome);
	lv_label_set_text(ui->screen_FirstBoot_Welcome_Header, "Welcome to\nyour new\nswitch pannel\n  ");
	lv_label_set_long_mode(ui->screen_FirstBoot_Welcome_Header, LV_LABEL_LONG_WRAP);
	lv_obj_set_pos(ui->screen_FirstBoot_Welcome_Header, 20, 295);
	lv_obj_set_size(ui->screen_FirstBoot_Welcome_Header, 680, 150);
	lv_obj_set_style_border_width(ui->screen_FirstBoot_Welcome_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_radius(ui->screen_FirstBoot_Welcome_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_color(ui->screen_FirstBoot_Welcome_Header, lv_color_hex(0xffffff), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui->screen_FirstBoot_Welcome_Header, &lumi_font_helvetica_40, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui->screen_FirstBoot_Welcome_Header, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_letter_space(ui->screen_FirstBoot_Welcome_Header, 2, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_line_space(ui->screen_FirstBoot_Welcome_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui->screen_FirstBoot_Welcome_Header, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(ui->screen_FirstBoot_Welcome_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_top(ui->screen_FirstBoot_Welcome_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_right(ui->screen_FirstBoot_Welcome_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_bottom(ui->screen_FirstBoot_Welcome_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_left(ui->screen_FirstBoot_Welcome_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_width(ui->screen_FirstBoot_Welcome_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);


	ui->screen_FirstBoot_Welcome_btn_getstarted = lv_btn_create(ui->screen_FirstBoot_Welcome);
	ui->screen_FirstBoot_Welcome_btn_getstarted_label = lv_label_create(ui->screen_FirstBoot_Welcome_btn_getstarted);
	lv_label_set_text(ui->screen_FirstBoot_Welcome_btn_getstarted_label, "Get started");
	lv_label_set_long_mode(ui->screen_FirstBoot_Welcome_btn_getstarted_label, LV_LABEL_LONG_WRAP);
	lv_obj_align(ui->screen_FirstBoot_Welcome_btn_getstarted_label, LV_ALIGN_CENTER, 0, 0);
	lv_obj_set_style_pad_all(ui->screen_FirstBoot_Welcome_btn_getstarted, 0, LV_STATE_DEFAULT);
	lv_obj_set_width(ui->screen_FirstBoot_Welcome_btn_getstarted_label, LV_PCT(100));
	lv_obj_set_pos(ui->screen_FirstBoot_Welcome_btn_getstarted, 20, 607);
	lv_obj_set_size(ui->screen_FirstBoot_Welcome_btn_getstarted, 680, 92);
	lv_obj_set_style_bg_opa(ui->screen_FirstBoot_Welcome_btn_getstarted, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_color(ui->screen_FirstBoot_Welcome_btn_getstarted, lv_color_hex(0x1c1c1c), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_grad_dir(ui->screen_FirstBoot_Welcome_btn_getstarted, LV_GRAD_DIR_NONE, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_border_width(ui->screen_FirstBoot_Welcome_btn_getstarted, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_radius(ui->screen_FirstBoot_Welcome_btn_getstarted, 50, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_width(ui->screen_FirstBoot_Welcome_btn_getstarted, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_color(ui->screen_FirstBoot_Welcome_btn_getstarted, lv_color_hex(0xffffff), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui->screen_FirstBoot_Welcome_btn_getstarted, &lumi_font_helvetica_40, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui->screen_FirstBoot_Welcome_btn_getstarted, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui->screen_FirstBoot_Welcome_btn_getstarted, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN|LV_STATE_DEFAULT);