	//No HC
	ui->screen_Setting_HomeController_NoHC_Header = lv_label_create(ui->screen_Setting_HomeController_NoHC);
	lv_label_set_text(ui->screen_Setting_HomeController_NoHC_Header, "Add to HC");
	lv_label_set_long_mode(ui->screen_Setting_HomeController_NoHC_Header, LV_LABEL_LONG_WRAP);
	lv_obj_set_pos(ui->screen_Setting_HomeController_NoHC_Header, 20, 33);
	lv_obj_set_size(ui->screen_Setting_HomeController_NoHC_Header, 680, 80);
	lv_obj_set_style_border_width(ui->screen_Setting_HomeController_NoHC_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_radius(ui->screen_Setting_HomeController_NoHC_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_color(ui->screen_Setting_HomeController_NoHC_Header, lv_color_hex(0xffffff), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui->screen_Setting_HomeController_NoHC_Header, &lv_font_montserrat_48, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui->screen_Setting_HomeController_NoHC_Header, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_letter_space(ui->screen_Setting_HomeController_NoHC_Header, 2, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_line_space(ui->screen_Setting_HomeController_NoHC_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui->screen_Setting_HomeController_NoHC_Header, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(ui->screen_Setting_HomeController_NoHC_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_top(ui->screen_Setting_HomeController_NoHC_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_right(ui->screen_Setting_HomeController_NoHC_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_bottom(ui->screen_Setting_HomeController_NoHC_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_left(ui->screen_Setting_HomeController_NoHC_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_width(ui->screen_Setting_HomeController_NoHC_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	
	ui->screen_Setting_HomeController_NoHC_btn_Addmanual = lv_btn_create(ui->screen_Setting_HomeController_NoHC);
	ui->screen_Setting_HomeController_NoHC_btn_Addmanual_label = lv_label_create(ui->screen_Setting_HomeController_NoHC_btn_Addmanual);
	lv_label_set_text(ui->screen_Setting_HomeController_NoHC_btn_Addmanual_label, "Add manual");
	lv_label_set_long_mode(ui->screen_Setting_HomeController_NoHC_btn_Addmanual_label, LV_LABEL_LONG_WRAP);
	lv_obj_align(ui->screen_Setting_HomeController_NoHC_btn_Addmanual_label, LV_ALIGN_CENTER, 0, 0);
	lv_obj_set_style_pad_all(ui->screen_Setting_HomeController_NoHC_btn_Addmanual, 0, LV_STATE_DEFAULT);
	lv_obj_set_width(ui->screen_Setting_HomeController_NoHC_btn_Addmanual_label, LV_PCT(100));
	lv_obj_set_pos(ui->screen_Setting_HomeController_NoHC_btn_Addmanual, 195, 404);
	lv_obj_set_size(ui->screen_Setting_HomeController_NoHC_btn_Addmanual, 330, 92);
	lv_obj_set_style_bg_opa(ui->screen_Setting_HomeController_NoHC_btn_Addmanual, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_color(ui->screen_Setting_HomeController_NoHC_btn_Addmanual, lv_color_hex(0x1c1c1c), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_grad_dir(ui->screen_Setting_HomeController_NoHC_btn_Addmanual, LV_GRAD_DIR_NONE, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_border_width(ui->screen_Setting_HomeController_NoHC_btn_Addmanual, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_radius(ui->screen_Setting_HomeController_NoHC_btn_Addmanual, 92, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_width(ui->screen_Setting_HomeController_NoHC_btn_Addmanual, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_color(ui->screen_Setting_HomeController_NoHC_btn_Addmanual, lv_color_hex(0xffffff), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui->screen_Setting_HomeController_NoHC_btn_Addmanual, &lv_font_montserrat_40, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui->screen_Setting_HomeController_NoHC_btn_Addmanual, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui->screen_Setting_HomeController_NoHC_btn_Addmanual, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN|LV_STATE_DEFAULT);

	ui->screen_Setting_HomeController_NoHC_label_NoHCfound = lv_label_create(ui->screen_Setting_HomeController_NoHC);
	lv_label_set_text(ui->screen_Setting_HomeController_NoHC_label_NoHCfound, "No HC found");
	lv_label_set_long_mode(ui->screen_Setting_HomeController_NoHC_label_NoHCfound, LV_LABEL_LONG_WRAP);
	lv_obj_set_pos(ui->screen_Setting_HomeController_NoHC_label_NoHCfound, 211, 304);
	lv_obj_set_size(ui->screen_Setting_HomeController_NoHC_label_NoHCfound, 297, 49);
	lv_obj_set_style_border_width(ui->screen_Setting_HomeController_NoHC_label_NoHCfound, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_radius(ui->screen_Setting_HomeController_NoHC_label_NoHCfound, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_color(ui->screen_Setting_HomeController_NoHC_label_NoHCfound, lv_color_hex(0xffffff), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui->screen_Setting_HomeController_NoHC_label_NoHCfound, &lv_font_montserrat_40, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui->screen_Setting_HomeController_NoHC_label_NoHCfound, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_letter_space(ui->screen_Setting_HomeController_NoHC_label_NoHCfound, 2, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_line_space(ui->screen_Setting_HomeController_NoHC_label_NoHCfound, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui->screen_Setting_HomeController_NoHC_label_NoHCfound, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(ui->screen_Setting_HomeController_NoHC_label_NoHCfound, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_top(ui->screen_Setting_HomeController_NoHC_label_NoHCfound, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_right(ui->screen_Setting_HomeController_NoHC_label_NoHCfound, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_bottom(ui->screen_Setting_HomeController_NoHC_label_NoHCfound, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_left(ui->screen_Setting_HomeController_NoHC_label_NoHCfound, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_width(ui->screen_Setting_HomeController_NoHC_label_NoHCfound, 0, LV_PART_MAIN|LV_STATE_DEFAULT);

    ui->screen_Setting_HomeController_NoHC_btn_AddtoHC = lv_btn_create(ui->screen_Setting_HomeController_NoHC);
	ui->screen_Setting_HomeController_NoHC_btn_AddtoHC_label = lv_label_create(ui->screen_Setting_HomeController_NoHC_btn_AddtoHC);
	lv_label_set_text(ui->screen_Setting_HomeController_NoHC_btn_AddtoHC_label, "Add to HC");
	lv_label_set_long_mode(ui->screen_Setting_HomeController_NoHC_btn_AddtoHC_label, LV_LABEL_LONG_WRAP);
	lv_obj_align(ui->screen_Setting_HomeController_NoHC_btn_AddtoHC_label, LV_ALIGN_CENTER, 0, 0);
	lv_obj_set_style_pad_all(ui->screen_Setting_HomeController_NoHC_btn_AddtoHC, 0, LV_STATE_DEFAULT);
	lv_obj_set_width(ui->screen_Setting_HomeController_NoHC_btn_AddtoHC_label, LV_PCT(100));
	lv_obj_set_pos(ui->screen_Setting_HomeController_NoHC_btn_AddtoHC, 20, 607);
	lv_obj_set_size(ui->screen_Setting_HomeController_NoHC_btn_AddtoHC, 680, 104);
	lv_obj_set_style_bg_opa(ui->screen_Setting_HomeController_NoHC_btn_AddtoHC, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_color(ui->screen_Setting_HomeController_NoHC_btn_AddtoHC, lv_color_hex(0x1c1c1c), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_grad_dir(ui->screen_Setting_HomeController_NoHC_btn_AddtoHC, LV_GRAD_DIR_NONE, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_border_width(ui->screen_Setting_HomeController_NoHC_btn_AddtoHC, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_radius(ui->screen_Setting_HomeController_NoHC_btn_AddtoHC, 50, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_width(ui->screen_Setting_HomeController_NoHC_btn_AddtoHC, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_color(ui->screen_Setting_HomeController_NoHC_btn_AddtoHC, lv_color_hex(0xacacac), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui->screen_Setting_HomeController_NoHC_btn_AddtoHC, &lv_font_montserrat_40, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui->screen_Setting_HomeController_NoHC_btn_AddtoHC, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui->screen_Setting_HomeController_NoHC_btn_AddtoHC, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN|LV_STATE_DEFAULT);

