
	ui->screen_Setting_Brightness_Header = lv_label_create(ui->screen_Setting_Brightness);
	lv_label_set_text(ui->screen_Setting_Brightness_Header, "Brightness");
	lv_label_set_long_mode(ui->screen_Setting_Brightness_Header, LV_LABEL_LONG_WRAP);
	lv_obj_set_pos(ui->screen_Setting_Brightness_Header, 20, 33);
	lv_obj_set_size(ui->screen_Setting_Brightness_Header, 680, 80);
	lv_obj_set_style_border_width(ui->screen_Setting_Brightness_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_radius(ui->screen_Setting_Brightness_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_color(ui->screen_Setting_Brightness_Header, lv_color_hex(0xffffff), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui->screen_Setting_Brightness_Header, &lumi_font_helvetica_48, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui->screen_Setting_Brightness_Header, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_letter_space(ui->screen_Setting_Brightness_Header, 2, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_line_space(ui->screen_Setting_Brightness_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui->screen_Setting_Brightness_Header, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(ui->screen_Setting_Brightness_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_top(ui->screen_Setting_Brightness_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_right(ui->screen_Setting_Brightness_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_bottom(ui->screen_Setting_Brightness_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_left(ui->screen_Setting_Brightness_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_width(ui->screen_Setting_Brightness_Header, 0, LV_PART_MAIN|LV_STATE_DEFAULT);

    ui->screen_btn_67 = lv_btn_create(ui->screen_Setting_Brightness);
	ui->screen_btn_67_label = lv_label_create(ui->screen_btn_67);
	lv_label_set_text(ui->screen_btn_67_label, "");
	lv_label_set_long_mode(ui->screen_btn_67_label, LV_LABEL_LONG_WRAP);
	lv_obj_align(ui->screen_btn_67_label, LV_ALIGN_CENTER, 0, 0);
	lv_obj_set_style_pad_all(ui->screen_btn_67, 0, LV_STATE_DEFAULT);
	lv_obj_set_width(ui->screen_btn_67_label, LV_PCT(100));
	lv_obj_set_pos(ui->screen_btn_67, 20, 118);
	lv_obj_set_size(ui->screen_btn_67, 680, 208);
	lv_obj_set_style_bg_opa(ui->screen_btn_67, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_color(ui->screen_btn_67, lv_color_hex(0x1C1C1C), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_grad_dir(ui->screen_btn_67, LV_GRAD_DIR_NONE, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_border_width(ui->screen_btn_67, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_radius(ui->screen_btn_67, 25, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_width(ui->screen_btn_67, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_color(ui->screen_btn_67, lv_color_hex(0xffffff), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui->screen_btn_67, &lv_font_montserrat_40, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui->screen_btn_67, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui->screen_btn_67, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN|LV_STATE_DEFAULT);

	ui->screen_line_2 = lv_line_create(ui->screen_Setting_Brightness);
	static lv_point_t screen_line_2[] ={{675, 0},{0, 0},};
	lv_line_set_points(ui->screen_line_2, screen_line_2, 2);
	lv_obj_set_pos(ui->screen_line_2, 24, 223);
	lv_obj_set_size(ui->screen_line_2, 672, 18);
	lv_obj_set_style_line_width(ui->screen_line_2, 2, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_line_color(ui->screen_line_2, lv_color_hex(0x757575), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_line_opa(ui->screen_line_2, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_line_rounded(ui->screen_line_2, true, LV_PART_MAIN|LV_STATE_DEFAULT);

	ui->screen_label_31 = lv_label_create(ui->screen_Setting_Brightness);
	lv_label_set_text(ui->screen_label_31, "Brightness");
	lv_label_set_long_mode(ui->screen_label_31, LV_LABEL_LONG_WRAP);
	lv_obj_set_pos(ui->screen_label_31, 27, 151);
	lv_obj_set_size(ui->screen_label_31, 331, 52);
	lv_obj_set_style_border_width(ui->screen_label_31, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_radius(ui->screen_label_31, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_color(ui->screen_label_31, lv_color_hex(0xffffff), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui->screen_label_31, &lumi_font_helvetica_40, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui->screen_label_31, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_letter_space(ui->screen_label_31, 2, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_line_space(ui->screen_label_31, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui->screen_label_31, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(ui->screen_label_31, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_top(ui->screen_label_31, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_right(ui->screen_label_31, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_bottom(ui->screen_label_31, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_left(ui->screen_label_31, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_width(ui->screen_label_31, 0, LV_PART_MAIN|LV_STATE_DEFAULT);

	ui->screen_Setting_Brightness_slide_ValueBrightness = lv_slider_create(ui->screen_Setting_Brightness);
    lv_obj_set_size(ui->screen_Setting_Brightness_slide_ValueBrightness, 632, 60);
    lv_obj_set_pos(ui->screen_Setting_Brightness_slide_ValueBrightness, 44,248);
    lv_obj_set_style_bg_color(ui->screen_Setting_Brightness_slide_ValueBrightness, lv_color_hex(0x000000), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui->screen_Setting_Brightness_slide_ValueBrightness, LV_OPA_COVER, LV_PART_MAIN); 
    lv_obj_set_style_bg_color(ui->screen_Setting_Brightness_slide_ValueBrightness, lv_color_hex(0x008c4f), LV_PART_INDICATOR);  
    lv_obj_set_style_bg_opa(ui->screen_Setting_Brightness_slide_ValueBrightness, LV_OPA_COVER, LV_PART_INDICATOR); 
    lv_obj_set_style_bg_opa(ui->screen_Setting_Brightness_slide_ValueBrightness, LV_OPA_TRANSP, LV_PART_KNOB); 
    lv_obj_set_style_border_width(ui->screen_Setting_Brightness_slide_ValueBrightness, 0, LV_PART_KNOB);
    lv_obj_set_style_pad_all(ui->screen_Setting_Brightness_slide_ValueBrightness, 0, LV_PART_KNOB);
    lv_slider_set_range(ui->screen_Setting_Brightness_slide_ValueBrightness, 0, 100);

	ui->screen_Setting_Brightness_label_ValueBrightness = lv_label_create(ui->screen_Setting_Brightness);
	lv_label_set_text(ui->screen_Setting_Brightness_label_ValueBrightness, "0");
	lv_label_set_long_mode(ui->screen_Setting_Brightness_label_ValueBrightness, LV_LABEL_LONG_WRAP);
	lv_obj_set_pos(ui->screen_Setting_Brightness_label_ValueBrightness, 560, 151);
	lv_obj_set_size(ui->screen_Setting_Brightness_label_ValueBrightness, 81, 52);
	lv_obj_set_style_border_width(ui->screen_Setting_Brightness_label_ValueBrightness, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_radius(ui->screen_Setting_Brightness_label_ValueBrightness, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_color(ui->screen_Setting_Brightness_label_ValueBrightness, lv_color_hex(0xffffff), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui->screen_Setting_Brightness_label_ValueBrightness, &lumi_font_helvetica_40, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui->screen_Setting_Brightness_label_ValueBrightness, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_letter_space(ui->screen_Setting_Brightness_label_ValueBrightness, 2, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_line_space(ui->screen_Setting_Brightness_label_ValueBrightness, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui->screen_Setting_Brightness_label_ValueBrightness, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(ui->screen_Setting_Brightness_label_ValueBrightness, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_top(ui->screen_Setting_Brightness_label_ValueBrightness, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_right(ui->screen_Setting_Brightness_label_ValueBrightness, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_bottom(ui->screen_Setting_Brightness_label_ValueBrightness, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_left(ui->screen_Setting_Brightness_label_ValueBrightness, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_width(ui->screen_Setting_Brightness_label_ValueBrightness, 0, LV_PART_MAIN|LV_STATE_DEFAULT);

	ui->screen_Setting_Brightness_label_Symbol = lv_label_create(ui->screen_Setting_Brightness);
	lv_label_set_text(ui->screen_Setting_Brightness_label_Symbol, "%");
	lv_label_set_long_mode(ui->screen_Setting_Brightness_label_Symbol, LV_LABEL_LONG_WRAP);
	lv_obj_set_pos(ui->screen_Setting_Brightness_label_Symbol, 636, 152);
	lv_obj_set_size(ui->screen_Setting_Brightness_label_Symbol, 50, 48);
	lv_obj_set_style_border_width(ui->screen_Setting_Brightness_label_Symbol, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_radius(ui->screen_Setting_Brightness_label_Symbol, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_color(ui->screen_Setting_Brightness_label_Symbol, lv_color_hex(0xffffff), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui->screen_Setting_Brightness_label_Symbol, &lumi_font_helvetica_40, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui->screen_Setting_Brightness_label_Symbol, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_letter_space(ui->screen_Setting_Brightness_label_Symbol, 2, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_line_space(ui->screen_Setting_Brightness_label_Symbol, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui->screen_Setting_Brightness_label_Symbol, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_opa(ui->screen_Setting_Brightness_label_Symbol, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_top(ui->screen_Setting_Brightness_label_Symbol, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_right(ui->screen_Setting_Brightness_label_Symbol, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_bottom(ui->screen_Setting_Brightness_label_Symbol, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_pad_left(ui->screen_Setting_Brightness_label_Symbol, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_width(ui->screen_Setting_Brightness_label_Symbol, 0, LV_PART_MAIN|LV_STATE_DEFAULT);

	ui->screen_Setting_Brightness_btn_Save = lv_btn_create(ui->screen_Setting_Brightness);
	ui->screen_Setting_Brightness_btn_Save_label = lv_label_create(ui->screen_Setting_Brightness_btn_Save);
	lv_label_set_text(ui->screen_Setting_Brightness_btn_Save_label, "Save");
	lv_label_set_long_mode(ui->screen_Setting_Brightness_btn_Save_label, LV_LABEL_LONG_WRAP);
	lv_obj_align(ui->screen_Setting_Brightness_btn_Save_label, LV_ALIGN_CENTER, 0, 0);
	lv_obj_set_style_pad_all(ui->screen_Setting_Brightness_btn_Save, 0, LV_STATE_DEFAULT);
	lv_obj_set_width(ui->screen_Setting_Brightness_btn_Save_label, LV_PCT(100));
	lv_obj_set_pos(ui->screen_Setting_Brightness_btn_Save, 20, 607);
	lv_obj_set_size(ui->screen_Setting_Brightness_btn_Save, 680, 92);
	lv_obj_set_style_bg_opa(ui->screen_Setting_Brightness_btn_Save, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_color(ui->screen_Setting_Brightness_btn_Save, lv_color_hex(0x1c1c1c), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_grad_dir(ui->screen_Setting_Brightness_btn_Save, LV_GRAD_DIR_NONE, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_border_width(ui->screen_Setting_Brightness_btn_Save, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_radius(ui->screen_Setting_Brightness_btn_Save, 50, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_width(ui->screen_Setting_Brightness_btn_Save, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_color(ui->screen_Setting_Brightness_btn_Save, lv_color_hex(0xffffff), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui->screen_Setting_Brightness_btn_Save, &lumi_font_helvetica_40, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui->screen_Setting_Brightness_btn_Save, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui->screen_Setting_Brightness_btn_Save, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN|LV_STATE_DEFAULT);

	ui->screen_Setting_Brightness_btn_Return = lv_btn_create(ui->screen_Setting_Brightness);
	ui->screen_Setting_Brightness_btn_Return_label = lv_label_create(ui->screen_Setting_Brightness_btn_Return);
	lv_label_set_text(ui->screen_Setting_Brightness_btn_Return_label, "" LV_SYMBOL_LEFT "");
	lv_label_set_long_mode(ui->screen_Setting_Brightness_btn_Return_label, LV_LABEL_LONG_WRAP);
	lv_obj_align(ui->screen_Setting_Brightness_btn_Return_label, LV_ALIGN_CENTER, 0, 0);
	lv_obj_set_style_pad_all(ui->screen_Setting_Brightness_btn_Return, 0, LV_STATE_DEFAULT);
	lv_obj_set_width(ui->screen_Setting_Brightness_btn_Return_label, LV_PCT(100));
	lv_obj_set_pos(ui->screen_Setting_Brightness_btn_Return, 10, 10);
	lv_obj_set_size(ui->screen_Setting_Brightness_btn_Return, 72, 72);
	lv_obj_set_style_bg_opa(ui->screen_Setting_Brightness_btn_Return, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_color(ui->screen_Setting_Brightness_btn_Return, lv_color_hex(0x1c1c1c), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_bg_grad_dir(ui->screen_Setting_Brightness_btn_Return, LV_GRAD_DIR_NONE, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_border_width(ui->screen_Setting_Brightness_btn_Return, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_radius(ui->screen_Setting_Brightness_btn_Return, 50, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_shadow_width(ui->screen_Setting_Brightness_btn_Return, 0, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_color(ui->screen_Setting_Brightness_btn_Return, lv_color_hex(0xffffff), LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui->screen_Setting_Brightness_btn_Return, &lv_font_montserrat_40, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_opa(ui->screen_Setting_Brightness_btn_Return, 255, LV_PART_MAIN|LV_STATE_DEFAULT);
	lv_obj_set_style_text_align(ui->screen_Setting_Brightness_btn_Return, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN|LV_STATE_DEFAULT);